name: Trigger pnpm sync in codevault

on: [push]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - name: Dispatch to codevault
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.ALGOVAULT_PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/arpanxneuro/algovaultx/dispatches \
          -d '{"event_type":"pnpm-sync"}'
